### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by LegalHackersNatal** [dnovaes/chatbot-cdc#8]
Olá, @dnovaes ! Fazemos parte de um grupo chamado Legal Hackers, que reune pessoas com interesse em Direito e Tecnologia. Seu chatbot sobre o CDC parece uma ótima ideia, que pode ter um enorme impacto social. Talvez possamos trabalhar em conjunto para desenvolvê-lo ainda mais. Se você quiser, podemos conversar melhor sobre esse assunto. Como podemos lhe contactar? Obrigado e, desde já, parabéns!

**Comment by dnovaes** [comment]
Bom dia! Agradeço o contato e o reconhecimento. Estou aberto a discussão. Podem me encontrar via:
gmail: novaesdigo@gmail.com
skype: novaes.diego

Pelo chat do gmail acredito que possamos conversar melhor. att
